version: '3.9'
services:
  flask-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_USERNAME: sa
      DB_PASSWORD: sa123
      DB_SERVER: mssql
      DB_DATABASE: 4K
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: sa123
      ACCEPT_EULA: "Y"
